# Generated by Django 3.2.6 on 2021-08-31 18:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoWebApp', '0002_auto_20210829_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='severity',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Baja', 'Baja')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
