# Generated by Django 3.2.6 on 2021-09-04 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210902_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categorias',
            field=models.ManyToManyField(choices=[('Resuelto', 'Resuelto'), ('En proceso', 'En Proceso'), ('Planeado', 'Planeado')], to='blog.Categoria'),
        ),
    ]
